### ISSUE TITLE
Postup/PostDown rules besides 'peer based' rules 

### ISSUE THREAD

**Issue by thecoshman** [vijaygill/wg-ui-plus#17]
In #14 you are setting things up to configure the IPTable rules based on the peers that are configured. But if I'm not mistaken, we also want a way to provide the IP masquerading rules that handle the NAT issues of WG running within Docker

**Comment by vijaygill** [comment]
@thecoshman 
With the way this project is progressing, I think this is not required anymore. The users can live with the IPTables rules generated by the app or find some other solution.
