### ISSUE TITLE
'Proper' http methods for rest API

### ISSUE THREAD

**Issue by thecoshman** [vijaygill/wg-ui-plus#19]
POST means create a brand new resource - a new identifier would be generated by the server
PUT means create/replace a resource with a brand new version, but identifier remains same
PATCH means partially update a resource

IMO, 
* C -> POST -> never accept ID in the request, server will generate and create new resource, if valid payload
* R -> GET
* U -> PUT -> Considering our payloads are fairly small, can probably just say that UI sends a FULL new version to update, client must provide an ID that already exists, else it's a bad request
* D -> DELETE

**Comment by vijaygill** [comment]
Closing as it uses Django which forces this pattern.
