### ISSUE TITLE
Default values to 'tweak'

### ISSUE THREAD

**Issue by thecoshman** [vijaygill/wg-ui-plus#51]
I would argue that by default, the WAN port should default to `51820` - yes there's something to be said for not using default ports for services, but the security advantages there is fairly minimal.

The default WAN IP could probably do some sort of "what's my ip" look up to automatically detect what your public IP is.

Probably not have the `Laptop` and `Mobile Phone` peers there by default.

**Comment by vijaygill** [comment]
@thecoshman 
Those port numbers sort of got stuck in my mind after having read so many articles on WireGuard.
It's not a bug and the values can be changed when someone sets up the VPN.
Does not need any work from coding point of view.
Closing this issue.
