### ISSUE TITLE
Peer list to show 'all' peers, not just those that are/have connected

### ISSUE THREAD

**Issue by thecoshman** [vijaygill/wg-ui-plus#52]
If a peer is configured, which by default there's two, they should always show up in the home/dashboard with the last handshake saying 'never' if they've never connected.

**Comment by vijaygill** [comment]
@thecoshman - that list comes from wireguard's own output. I just parse it and display on the screen. Leaving some column values blank is cleaner than showing some information.
Closing this ticket.
