### ISSUE TITLE
Editing peers is different from Viewing a peer

### ISSUE THREAD

**Issue by thecoshman** [vijaygill/wg-ui-plus#53]
The edit peer mode should be distinct from viewing a peer (two separate buttons).

The main 'peer' menu where they are all listed should be able to directly delete a peer.

Add a tool hint for the `IP Address` field explaining what it means, and why can't it be edited?

When deleting a peer, the confirmation should include what it is you are confirming. And apparently there's an error when I try to delete the default `Laptop` peer " Fix the errors before saving. Warnings can be ignored. ".

That warning shouldn't move the buttons across

Move the 'add peer' button to the top, above the table, and give it a clear name 'add peer'.

**Comment by vijaygill** [comment]
Editing and viewing can remain the same. Not going to write code for something which does not cause any issues.
I have plans for deleting objects from the list page itself. Will do it in next phase.
IP address field has field has tool-tip now.
Warning now appears below the buttons.
That add-button - I am still not sure where it should appear. I have tried options like above the table, below the table. They all look equally ugly.
