### ISSUE TITLE
Server Config UI tweaks

### ISSUE THREAD

**Issue by thecoshman** [vijaygill/wg-ui-plus#54]
When you click `ok` provide feedback

When you click 'Generate Config' provide feedback.

Tool tips for what 'Generate Config' and 'ok' are going to do.

'Local Networks' isn't clear to me what it's going to do... is that a 'black list' of IP/Ranges that you do not want Peers to be able to access? Are you able to set that as a default for peers, and then give certain peers special access that overrides this default? Does this even make sense in the server section?

Show 'dirty' fields, ie, if I've changed stuff but not saved it, show that on the UI, perhaps with a per field 'revert'.

Considering the left menu is (mostly) all about configuration, just rename the `Server Configuration` menu option to `Server`.

Show when the saved config differs from what has been pushed to WG since last restart, or that a restart is required to apply changes.

**Comment by vijaygill** [comment]
@thecoshman 
The feedback is there when the configuration files are generated and also when WG is restarted. What extra feedback do you expect?

![image](https://github.com/vijaygill/wg-ui-plus/assets/8999486/d885eecd-b3db-4aac-bf2f-fb999f58835b)

Menu item renamed to just "Server".

All those changes to show dirty fields / field-level undo is too much work for this small project.

the last one to show time difference between saving of data and config files is already a ticket.
