### ISSUE TITLE
Show current version and availability of upgrades

### ISSUE THREAD

**Issue by thecoshman** [vijaygill/wg-ui-plus#55]
Might need to wait for a proper v1 - but the version of the system should be shown, along with a subtle warning that there's updates, perhaps less subtle if the current version has been flagged for some reason, like vulnerabilities. Obviously being docker based, can't really make the system self up-gradable, but a solid warning would go a long way.

**Comment by vijaygill** [comment]
@thecoshman 
This will have to wait until we have v1.0.
This will require some kind of usage of REST api from github to get versions and compare the one that's running.
This will soon go out of hand as there might be channels of versions too
stable versions - coming from master branch
dev versions - coming from develop branch
And then option to move between channels - people may choose to move from stable to dev or dev to stable.
For now, just let the users pull the right image and use it.

**Comment by vijaygill** [comment]
@thecoshman - it is done (hopefully). Download v1.2.13 and let me know.
