### ISSUE TITLE
Without being logged in, you get access

### ISSUE THREAD

**Issue by thecoshman** [vijaygill/wg-ui-plus#57]
Started up the container as per the readme, open the browser page and get the following
![image](https://github.com/vijaygill/wg-ui-plus/assets/4427990/793be36e-402f-4bb2-b144-601f0a200753)

**Comment by vijaygill** [comment]
@thecoshman Done - pushiing changes soon.
![image](https://github.com/vijaygill/wg-ui-plus/assets/8999486/929039d1-fc5b-41f1-aeb8-650d7271cd7f)
