### ISSUE TITLE
Suspect CORS issue

### ISSUE THREAD

**Issue by thecoshman** [vijaygill/wg-ui-plus#65]
When running the service, I am able to use the web-ui if I am accessing the container directly via the http port, but seems if I use a reverse proxy, nginx in my case, even though I am meant to be logged in, trying to create a new peer results in the logs showing that I am forbidden

> Forbidden: /api/v1/data/peer/
> 2024-06-12 05:34:59,001 WARNING django.request Forbidden: /api/v1/data/peer/
> 2024-06-12 05:34:59,003 WARNING django.server "POST /api/v1/data/peer/ HTTP/1.0" 403 193

The nginx config for this virtual server is the same as what I use for all my other containers without issue, so unless this app requires something special, it believe it's the app that is the issue here.

**Comment by vijaygill** [comment]
@thecoshman - I am not sure how your reverse-proxy is setup. I have it behind nginx reverse-proxy too and it just works. Have you got the permissions issue on data files sorted?

**Comment by thecoshman** [comment]
So we got to the bottom of this, the app wasn't accepting trusted origins, and there was no way to configure this. A new update will soon be published I am promised that will allow you set this in the compose file, so you can set an env variable like `CSRF_TRUSTED_ORIGINS=https://wg-ui-plus.example.com` and then the Python app is happy being sat behind a reverse proxy.
